### ISSUE TITLE
Uso do window no script

### ISSUE THREAD

**Issue by Marlysson** [joaocarvalhowd/finducep.js#1]
Por que você usou a associação do teu objeto ao objeto window do browser?

e outra.. O exports é feature do ES6? Para poder usar a função importando de outro arquivo?

**Comment by joaocarvalhowd** [comment]
**1- Por que você usou a associação do teu objeto ao objeto window do browser?**
Caso eu não faça essa associação ao objeto window, não é possivel você instanciar usando:

`new FindUCep()`

**2- O exports é feature do ES6? Para poder usar a função importando de outro arquivo?**
Sim é uma feature do ES6, para caso você queira importar ele dessa forma:
`import FindUCep from 'FindUCep';`

**Comment by Marlysson** [comment]
No segundo caso precisa usar tipo o Babel pra fazer transpiler? ou alguns
browsers já aceitam nativo..

Em 13 de dezembro de 2016 12:55, João Carvalho <notifications@github.com>
escreveu:

**Comment by joaocarvalhowd** [comment]
@Marlysson Teria que usar um webpack com babel. Segundo o mdn: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Statements/import ainda não é aceito por nenhum browser.

**Comment by Marlysson** [comment]
Vlw pela explicação..
